# !/bin/bash
set -e

KUBERNETES_DEPLOYMENT_NAME=""
KUBERNETES_MANIFEST_FILE_PATH=""
AZURE_CONTAINER_REGISTRY=""
IMAGE_TAG=""

while getopts d:r:t:f: flag
do
    case "${flag}" in
        d) KUBERNETES_DEPLOYMENT_NAME=${OPTARG};;
        f) KUBERNETES_MANIFEST_FILE_PATH=${OPTARG};;
        r) AZURE_CONTAINER_REGISTRY=${OPTARG};;
        t) IMAGE_TAG=${OPTARG};;
    esac
done

grep ${AZURE_CONTAINER_REGISTRY}/${KUBERNETES_DEPLOYMENT_NAME} $KUBERNETES_MANIFEST_FILE_PATH | while read -r line ; do
    KUBERNETES_POD_EXISTING_TAG=$(echo $line | sed 's|image: ||g' | cut -d ':' -f 2)
    KUBERNETES_POD_EXISTING_IMAGE="${AZURE_CONTAINER_REGISTRY}/${KUBERNETES_DEPLOYMENT_NAME}:${KUBERNETES_POD_EXISTING_TAG}"
    KUBERNETES_POD_NEW_IMAGE="${AZURE_CONTAINER_REGISTRY}/${KUBERNETES_DEPLOYMENT_NAME}:${IMAGE_TAG}"

    echo "$(sed "s|${KUBERNETES_POD_EXISTING_IMAGE}|${KUBERNETES_POD_NEW_IMAGE}|g" ${KUBERNETES_MANIFEST_FILE_PATH})" > $KUBERNETES_MANIFEST_FILE_PATH
    break
done

echo "::notice::Deployment manifest updated with new image: ${KUBERNETES_POD_NEW_IMAGE}"
