name: 'GitHub: Admin Repositories Settings'

on:
  workflow_dispatch:

# Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read
  actions: read

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  admin-update-repo-settings:
    name: 'GitHub: Update Repo Settings'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Update Repository Settings
        run: |
          bash ./admin/update_repo_settings.sh \
            -o ${{ github.repository_owner }} \
            -e ${{ github.ref_name }}
          
          echo "::notice::Release Published"
