name: 'GitHub: Fetch Updated Apps'

on:
  workflow_call:

# Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read
  actions: read

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  admin-fetch-updated-apps:
    name: 'GitHub: Fetch Updated Apps'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      
      - name: GitHub Configuration
        run: git config --global url."https://oauth2:${{ secrets.GH_TOKEN }}@github.com".insteadOf https://github.com

      - name: Clone cicd-deployment-scripts
        run: git clone https://github.com/code-kern-ai/cicd-deployment-scripts.git

      - name: Fetch Updated Apps
        run: |
          source ./cicd-deployment-scripts/admin/fetch_updated_apps.sh
          cp .env.${{ github.ref_name }} .env

          fetch_updated_apps ${{ github.repository_owner }}

          jq '.' diff.json
          
          echo "::notice::Updated Apps Fetched"

        # Save plan to artifacts  
      - name: Publish JSON diff
        uses: actions/upload-artifact@v4
        with:
            name: diff.json
            path: diff.json