name: 'Admin: Update GitHub Repositories Settings'

on:
  workflow_dispatch:

# Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read
  actions: read

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  admin-update-repo-settings:
    name: 'GitHub: Update Repo Settings'
    runs-on: ubuntu-latest
    steps:
      - name: Update Repository Settings
        run: |
          bash admin/update_repo_settings.sh \
            -e ${{ github.ref_name }}
          
          echo "::notice::Release Published"
