name: 'DC: Deploy'

on:
  workflow_call:

# Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  dc-deploy:
    name: 'DC: Deploy'
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'prod' && 'prod' || 'dev' }}
    steps:
      - name: Execute remote SSH deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: /bin/sh ./trigger_dev_deployment.sh

  gh-delete-branch:
    name: 'GitHub: Delete Branch'
    runs-on: ubuntu-latest
    environment: dev
    needs: [dc-deploy]
    if: github.event_name == 'pull_request' && github.event.pull_request.merged && !failure() && !cancelled()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GH_TOKEN }}
      
      - name: Delete Branch
        shell: bash
        run: git push origin --delete ${{ github.head_ref }} || true
