name: 'K8: Edit'

on:
  workflow_call:

# Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read
  actions: read

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  k8-edit:
    name: 'K8: Edit'
    runs-on: [self-hosted, "${{ github.event_name == 'release' && 'prod' || github.event.pull_request.base.ref }}"]
    environment: ${{ github.event_name == 'release' && 'prod' || 'dev' }}
    env:
      KUBERNETES_CLUSTER_REPO_NAME: "${{ vars.KUBERNETES_CLUSTER_REPO_NAME }}"
      KUBERNETES_MANIFEST_FILE_PATH: "${{ vars.KUBERNETES_MANIFEST_PATH }}/deployment.yml"
      AZURE_CONTAINER_REGISTRY: "${{ vars.AZURE_CONTAINER_REGISTRY }}"
      IMAGE_TAG: ${{ github.event_name == 'release' && github.event.release.tag_name || github.sha }}
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_TOKEN }}
        repository: ${{ github.repository_owner }}/${{ env.KUBERNETES_CLUSTER_REPO_NAME }}
        ref: refs/heads/dev
    
    - name: GitHub Configuration
      run: git config --global url."https://oauth2:${{ secrets.GH_TOKEN }}@github.com".insteadOf https://github.com

    - name: Clone cicd-deployment-scripts
      run: git clone https://github.com/code-kern-ai/cicd-deployment-scripts.git

    - name: Perform Edit/Git Operations
      shell: bash
      run: |
        AUTOMATED_RELEASE_BRANCH="automated-release-${{ github.event_name == 'release' && 'prod' || 'dev' }}"
        KUBERNETES_POD_NEW_IMAGE="${{ env.AZURE_CONTAINER_REGISTRY }}/${{ github.event.repository.name }}"
        
        AUTOMATED_RELEASE_BRANCH_EXISTS=$(git rev-parse --verify refs/heads/$AUTOMATED_RELEASE_BRANCH 2>/dev/null || true)
        git checkout $AUTOMATED_RELEASE_BRANCH || git checkout -b $AUTOMATED_RELEASE_BRANCH
        git push origin $AUTOMATED_RELEASE_BRANCH && git pull origin $AUTOMATED_RELEASE_BRANCH

        bash cicd-deployment-scripts/k8s/edit.sh \
          -d ${{ github.event.repository.name }} \
          -f ${{ env.KUBERNETES_MANIFEST_FILE_PATH }} \
          -r ${{ env.AZURE_CONTAINER_REGISTRY }} \
          -t ${{ env.IMAGE_TAG }}

        git config --global user.email "devtools@kern.ai"
        git config --global user.name "GitHub Actions"

        git add ${{ env.KUBERNETES_MANIFEST_FILE_PATH }}
        git commit -m "ci(${{ github.event.repository.name }}): ${{ env.IMAGE_TAG }}" || true
        git push origin $AUTOMATED_RELEASE_BRANCH

        PR_TITLE="ci: $AUTOMATED_RELEASE_BRANCH"
        if [ ${{ github.event_name }} == 'release' ]; then
          PR_TITLE="ci(${{ github.ref_name }}): $AUTOMATED_RELEASE_BRANCH"
        fi

        bash cicd-deployment-scripts/gh/pr_create.sh \
          -b ${{ github.event_name == 'release' && 'prod' || 'dev' }} \
          -h "$AUTOMATED_RELEASE_BRANCH" \
          -t "$PR_TITLE" \
          -o "${{ github.repository_owner }}" \
          -r "${{ github.event.repository.name }}" \
          -n "${{ github.event_name == 'release' && github.event.release.tag_name || github.event.pull_request.number }}" \
          -k "${{ env.KUBERNETES_CLUSTER_REPO_NAME }}" \