name: 'Parent Images: Build'

on:
  workflow_call:

# Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read
  actions: read

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  pi-build:
    name: 'Parent Images: Build Requirements'
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: ${{ vars.PYTHON_VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
    
      - name: GitHub Configuration
        run: git config --global url."https://oauth2:${{ secrets.GH_TOKEN }}@github.com".insteadOf https://github.com

      - name: Clone cicd-deployment-scripts
        run: git clone --branch parent-images https://github.com/code-kern-ai/cicd-deployment-scripts.git
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Run build
        run: |
          bash cicd-deployment-scripts/pi/build.sh \
            -p "${{ github.event.pull_request.number }}" \
            -r "${{ github.repository.default_branch }}" \