name: 'Parent Images: Build'

on:
  workflow_call:

# # Special permissions required for OIDC authentication
# permissions:
#   id-token: write
#   contents: read
#   actions: read

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  pi-compile:
    name: 'Parent Images: Compile Requirements'
    runs-on: ubuntu-latest
    environment: dev
    env:
      PYTHON_VERSION: ${{ vars.PYTHON_VERSION }}
    outputs:
      updated_parent_types: ${{ steps.run-compile.outputs.updated_parent_types }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/refinery-submodule-parent-images
          ref: ${{ github.event.pull_request.head.ref }}
    
      - name: GitHub Configuration
        run: git config --global url."https://oauth2:${{ secrets.GH_TOKEN }}@github.com".insteadOf https://github.com

      - name: Clone cicd-deployment-scripts
        run: git clone --branch parent-images https://github.com/code-kern-ai/cicd-deployment-scripts.git

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: python -m pip install pip-tools

      - name: Run compile
        id: run-compile
        run: |
          bash cicd-deployment-scripts/pi/compile.sh \
            -p "${{ github.event.pull_request.number }}"

  # pi-upload-artifacts:
  #   name: 'Parent Images: Upload Artifacts'
  #   runs-on: ubuntu-latest
  #   needs: pi-compile
  #   environment: dev
  #   env:
  #     PYTHON_VERSION: ${{ vars.PYTHON_VERSION }}
  #   strategy:
  #     matrix:
  #       parent_image_type: ${{ fromJson(needs.pi-compile.outputs.updated_parent_types) }}
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #       with:
  #         repository: ${{ github.repository_owner }}/refinery-submodule-parent-images
  #         ref: ${{ github.event.pull_request.head.ref }}
      
  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: ${{ env.PYTHON_VERSION }}

  #     - name: Install dependencies
  #       run: python -m pip install pip-tools
      
  #     - name: Compile Artifacts
  #       run: pip-compile requirements/${{ matrix.parent_image_type }}-requirements.in
      
  #     # Save plan to artifacts  
  #     - name: Upload ${{ matrix.parent_image_type }}-requirements
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: ${{ matrix.parent_image_type }}-requirements.txt
  #         path: requirements/${{ matrix.parent_image_type }}-requirements.txt
  #         if-no-files-found: error

  pi-build:
    name: 'Parent Images: Docker Build'
    runs-on: ubuntu-latest
    needs: [pi-compile]
    environment: dev
    env:
      PYTHON_VERSION: ${{ vars.PYTHON_VERSION }}
      DEV_CONTAINER_REGISTRY: ${{ vars.DEV_CONTAINER_REGISTRY }}
      DEV_LOGIN_USERNAME: ${{ secrets.DEV_LOGIN_USERNAME }}
      DEV_LOGIN_PASSWORD: ${{ secrets.DEV_LOGIN_PASSWORD }}
      IMAGE_TAG: ${{ github.event_name == 'release' && github.event.release.tag_name || github.event.pull_request.head.ref }}
    strategy:
      matrix:
        parent_image_type: ${{ fromJson(needs.pi-compile.outputs.updated_parent_types) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: '${{ github.repository_owner }}/refinery-${{ matrix.parent_image_type }}-parent-image'
          submodules: 'true'
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: python -m pip install pip-tools
      
      - name: Update submodules
        run: |
          echo "ls -l: $(pwd)"
          ls -l
          # cat ${{ github.workspace }}/submodules/parent-images/requirements/${{ matrix.parent_image_type }}-requirements.txt
          cd submodules
          echo "ls -l: $(pwd)"
          ls -l
          cd parent-images
          echo "ls -l: $(pwd)"
          ls -l

      - name: Compile Artifacts
        run: |
          cd ${{ github.workspace }}/submodules/parent-images
          git fetch origin && git checkout ${{ github.event.pull_request.head.ref }}
          pip-compile submodules/parent-images/requirements/${{ matrix.parent_image_type }}-requirements.in
      
      # # Download requirements from artifacts  
      # - name: Download ${{ matrix.parent_image_type }}-requirements
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: ${{ matrix.parent_image_type }}-requirements.txt
      #     path: ${{ github.workspace }}/submodules/parent-images/requirements

      # - name: GitHub Configuration
      #   run: git config --global url."https://oauth2:${{ secrets.GH_TOKEN }}@github.com".insteadOf https://github.com

      # - name: Clone cicd-deployment-scripts
      #   run: git clone --branch parent-images https://github.com/code-kern-ai/cicd-deployment-scripts.git

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64,arm

      - name: Log into DEV registry
        uses: docker/login-action@v3
        with:
          registry: "${{ env.DEV_CONTAINER_REGISTRY }}"
          username: "${{ env.DEV_LOGIN_USERNAME }}"
          password: "${{ env.DEV_LOGIN_PASSWORD }}"

      - name: Build & Push refinery-${{ matrix.parent_image_type }}-parent-image:dev
        uses: docker/build-push-action@v5
        with:
          context: .
          cache-from: type=registry,ref=${{ env.DEV_CONTAINER_REGISTRY }}/refinery-parent-images:dev-${{ matrix.parent_image_type }}-cache
          cache-to: type=registry,ref=${{ env.DEV_CONTAINER_REGISTRY }}/refinery-parent-images:dev-${{ matrix.parent_image_type }}-cache,mode=max,image-manifest=true
          platforms: linux/amd64
          file: Dockerfile
          tags: ${{ env.DEV_CONTAINER_REGISTRY }}/refinery-parent-images:dev-${{ matrix.parent_image_type }}
          push: true
          build-args: |
            platform=linux/amd64
            label=dockerfile-path=https://github.com/refinery-${{ matrix.parent_image_type }}-parent-image/blob/${{ github.sha }}/Dockerfile

      # - name: Build & Push refinery-${{ matrix.parent_image_type }}-parent-image:dev-arm64
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     cache-from: type=registry,ref=${{ env.DEV_CONTAINER_REGISTRY }}/refinery-parent-images:dev-${{ matrix.parent_image_type }}-arm64-cache
      #     cache-to: type=registry,ref=${{ env.DEV_CONTAINER_REGISTRY }}/refinery-parent-images:dev-${{ matrix.parent_image_type }}-arm64-cache,mode=max,image-manifest=true
      #     platforms: linux/arm64
      #     file: Dockerfile
      #     tags: ${{ env.DEV_CONTAINER_REGISTRY }}/refinery-parent-images:dev-${{ matrix.parent_image_type }}-arm64
      #     push: true
      #     build-args: |
      #       platform=linux/arm64
      #       label=dockerfile-path=https://github.com/refinery-${{ matrix.parent_image_type }}-parent-image/blob/${{ github.sha }}/Dockerfile

      # - name: Build & Push refinery-${{ matrix.parent_image_type }}-parent-image:sha
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     cache-from: type=registry,ref=${{ env.DEV_CONTAINER_REGISTRY }}/refinery-parent-images:${{ github.sha }}-${{ matrix.parent_image_type }}-cache
      #     cache-to: type=registry,ref=${{ env.DEV_CONTAINER_REGISTRY }}/refinery-parent-images:${{ github.sha }}-${{ matrix.parent_image_type }}-cache,mode=max,image-manifest=true
      #     platforms: linux/amd64
      #     file: Dockerfile
      #     tags: ${{ env.DEV_CONTAINER_REGISTRY }}/refinery-parent-images:${{ github.sha }}-${{ matrix.parent_image_type }}
      #     push: true
      #     build-args: |
      #       platform=linux/amd64
      #       label=dockerfile-path=https://github.com/refinery-${{ matrix.parent_image_type }}-parent-image/blob/${{ github.sha }}/Dockerfile

      # - name: Build & Push refinery-${{ matrix.parent_image_type }}-parent-image:sha-arm64
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     cache-from: type=registry,ref=${{ env.DEV_CONTAINER_REGISTRY }}/refinery-parent-images:${{ github.sha }}-${{ matrix.parent_image_type }}-arm64-cache
      #     cache-to: type=registry,ref=${{ env.DEV_CONTAINER_REGISTRY }}/refinery-parent-images:${{ github.sha }}-${{ matrix.parent_image_type }}-arm64-cache,mode=max,image-manifest=true
      #     platforms: linux/arm64
      #     file: Dockerfile
      #     tags: ${{ env.DEV_CONTAINER_REGISTRY }}/refinery-parent-images:${{ github.sha }}-${{ matrix.parent_image_type }}-arm64
      #     push: true
      #     build-args: |
      #       platform=linux/arm64
      #       label=dockerfile-path=https://github.com/refinery-${{ matrix.parent_image_type }}-parent-image/blob/${{ github.sha }}/Dockerfile
