name: "Python: Release"

on:
  workflow_call:

permissions:
  contents: write
  pull-requests: write

jobs:
  py-release:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          release-type: python
