name: "OpenTofu: Release"

on:
  workflow_call:

  push:
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write

jobs:
  tf-module-release:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          release-type: simple
