name: "OpenTofu: Generate Docs"

on:
  workflow_call:

permissions:
  contents: write
  pull-requests: write

jobs:
  tf-module-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render OpenTofu docs and push changes back to PR
      uses: terraform-docs/gh-actions@v1.1.0
      with:
        working-dir: .
        output-file: README.md
        output-method: inject
        git-push: "true"
