name: "GitHub: Validate Release"

on:
  workflow_call:

jobs:
  validate-release:
    name: 'GitHub: Validate Release'
    runs-on: ubuntu-latest
    steps:
      - name: Validate Release Tag
        shell: bash
        run: |
          if [[ ! "${{ github.event.release.tag_name }}" =~ ^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$ ]]; then
            echo "::error::Release Tag needs to match 'v[0-9]+.[0-9]+'"
            echo "More info: https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string"
            exit 1
          fi
